package com.flow.agent.filter;

import net.bytebuddy.description.method.MethodDescription;

/**
 * Skips JVM-generated bridge methods.
 *
 * <p>Bridge methods are synthetic methods generated by the compiler for generic type
 * covariance and covariant return types. They are not in the static graph and must be excluded.
 */
public class BridgeMethodFilter {

    /**
     * @return {@code true} if the method should be skipped (not instrumented)
     */
    public boolean shouldSkip(MethodDescription method) {
        return method.isBridge();
    }
}

